### ISSUE TITLE
smartcard installed but not found?

### ISSUE THREAD

**Issue by ksolveson-p** [fasferraz/SWu-IKEv2#1]
Hi Fabricio,

I cloned the project to an Ubuntu 20 VM, and began to install the python modules that swu_emulator.py requires, but ran into the following:

![image](https://user-images.githubusercontent.com/60717654/128773613-27491cf9-bd2f-40f9-9b7d-e304ef3414c2.png)

However, when I try to install the smartcard module, I’m informed that it’s already installed.   So, in short, I’m stuck.   Any ideas?

![image](https://user-images.githubusercontent.com/60717654/128773661-a2afc9ab-027a-43ed-a18e-d8eb2134db7a.png)

Thanks in advance for any insights

**Comment by fasferraz** [comment]
Hi,

Thanks for reporting this error.
That is not the correct module. The correct module you need to install is pyscard (https://pypi.org/project/pyscard/#files).
I will update my project description with this information, in case others have the same issue.

In my case, using the pip3 install pyscard command did not worked.
I followed this approach (http://raspberrypi4u.blogspot.com/2018/01/raspberry-pi-smartcard-reader-thai-id.html)

sudo apt-get install pcscd git python-setuptools swig gcc libpcsclite-dev python-dev

git clone https://github.com/LudovicRousseau/pyscard.git
cd pyscard
sudo python3 setup.py build_ext install

In your case the last line should by python and not python3, since version 3 is your default version, right?

regards,
Fabricio

**Comment by ksolveson-p** [comment]
Hi Fabricio,

Thanks for the quick response!  Will follow steps described in your email.

Yes, using virtual python environment where python3 is the default.

Kevin

**Comment by ksolveson-p** [comment]
Hi Fabricio,

I don't know what sort of state I'd gotten into with my previous module installation attempts, but at any rate, the following steps finally worked:

1) Abandoned use of virtual python environment.
2) Made a new directory to re-clone your repo and re-cloned (to start with fresh slate)
3) Remaining steps as shown in following screenshot:

![image](https://user-images.githubusercontent.com/60717654/128915269-7da1a7ca-cb20-4483-a514-20fa48a8da6e.png)

Now, when I run "python3 swu_emulator.py -help" I get "No module named 'CryptoMobile'" (as shown in following screenshot).   Before I run amuck again, I want to verify: is https://github.com/P1sec/CryptoMobile the module I want? 

![image](https://user-images.githubusercontent.com/60717654/128916033-c09854eb-00f3-4d35-9a28-cc768b15b1c0.png)

Thanks in advance for the guidance!

Kevin

**Comment by fasferraz** [comment]
Hi,
yes, that's the module.
It's only used to run the milenage algortihm when you define the card details (Ki, OPc, OP) in the CLI instead of using a real USIM (either through smartcard reader or modem). If you don't want or need to use this feature, you may comment the lines.

**Comment by ksolveson-p** [comment]
Thanks, Fabricio!

**Comment by ksolveson-p** [comment]
Hi Fabricio,

Dialer running fine now, so I'm closing this issue.   Thank you for the help!  

FYI - I'm using your Dialer to communicate with an ePDG emulator I'm trying to build.   Are you aware of anything out there that I could use as a starting point for the ePDG?   What did you use to test/debug your Dialer?

Thanks,
Kevin

**Comment by fasferraz** [comment]
I used a real ePDG in my development. I'm not aware of any open source ePDG, but i didn't did any research on that...

**Comment by ksolveson-p** [comment]
Thanks, Fabricio!
