### ISSUE TITLE
ike_decoded_ok not defined

### ISSUE THREAD

**Issue by ksolveson-p** [fasferraz/SWu-IKEv2#2]
Hi Fabricio,

Was adding some logging (to my local version, of course) and got the following error:

![image](https://user-images.githubusercontent.com/60717654/129448406-afb5d91e-e35f-4c37-811c-62bb8c006a8a.png)

So, I added "self.ike_decoded_ok = False" to the set_variables method and this resolved the error.

**Comment by fasferraz** [comment]
Hi,
Since this variable is used to return the result of the ike decoding, i think is better to add that line in the def decode_ike(self, data). This way each time we start a decoding the variable is started at False. If you add that line in the def set_variables, it will work only for the first decoding. 
Can you try that?
How the exceptions in state1 didn't set that variable?

**Comment by ksolveson-p** [comment]
Hi Fabricio,

Yes, I see what you mean; thanks!  Moved definition as shown here:

[image: image.png]
